name: 'setup-oras-action'
description: 'Setup ORAS CLI for GitHub Actions'
author: 'Balena <hello@balena.io>'

inputs:
  version:
    description: 'The ORAS CLI release to install'
    required: false
    default: ' 1.2.0'

outputs:
  version:
    description: 'The ORAS CLI release that was installed'

runs:
  using: node20
  main: dist/index.js
